### ISSUE TITLE
IllegalArgumentException on deleteByPK(Object pk)

### ISSUE THREAD

**Issue by Reversor** [PastorGL/fastdao#2]
I receive exception when trying to delete by primary key with message:
Can not set java.lang.Long field com.example.Entity.id to java.lang.Long

[The link to the line where the exception retrieved](https://github.com/PastorGL/fastdao/blob/8de2684abfc1fff0507fe2030e0400204ea432d7/src/main/java/io/github/pastorgl/fastdao/FastDAO.java#L632)

**Comment by Reversor** [comment]
#3 add pull request

**Comment by PastorGL** [comment]
fixed in #3
